fail_fast: false
repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.942"
    hooks:

    - id: mypy
      name: mypy
      stages: [commit]
      language: system
      entry: poetry run mypy
      types: [python]
      files: "\
        ^app/models/\
        |services/\
       " 
      exclude: "\
        ^app/conf/\
        |core\
        |kafka\
        |pagination\
        |security/\
        |tests/\
       "   

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      name: isort
      stages: [commit]
      language_version: python3.10
      entry: poetry run isort
      types: [python]

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:  
    - id: black
      name: black
      stages: [commit]
      language: system
      entry: poetry run black
      types: [python]      

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:   
    - id: flake8
      name: flake8
      stages: [commit]
      language: system
      entry: poetry run flake8
      types: [python]   